---
theme: jekyll-theme-hacker
title: nmstate
description: A Declarative API for Host Network Management
github:
  repository_url: https://github.com/nmstate/nmstate
include:
 - nmstate.gpg
 - utils
markdown: kramdown
kramdown:
  input: GFM
